name: Build QMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull QMK Docker Image
        run: docker pull qmkfm/qmk_cli:latest

      - name: Compile firmware
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/qmk_firmware \
          -e SKIP_VERSION=1 \
          qmkfm/qmk_cli \
          qmk compile -kb ploopyco/trackball_nano -km default

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: ploopyco_trackball_nano_default_firmware
          path: ploopyco_trackball_nano_default.hex
