name: QMK Firmware Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QMK Docker Environment
        run: |
          docker pull qmkfm/qmk_cli:latest
          docker run --rm qmkfm/qmk_cli qmk setup --yes

      - name: Build firmware
        run: |
          docker run --rm -v ${{ github.workspace }}:/qmk_firmware qmkfm/qmk_cli \
          qmk compile -kb ploopyco/trackball_nano -km default

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: ploopy-trackball-nano-firmware
          path: keyboards/ploopyco/trackball_nano/default.hex
